/******************************************************************************
*  Generated by PSoC Designer 5.2.2551
******************************************************************************/
#include <m8c.h>
/*
*   PSoCGPIOINT.h
*   Data: 04 June, 2002
*   Copyright (c) Cypress Semiconductor 2012. All Rights Reserved.
*
*  This file is generated by the Device Editor on Application Generation.
*  It contains equates that are useful in writing code relating to GPIO
*  related values.
*  
*  DO NOT EDIT THIS FILE MANUALLY, AS IT IS OVERWRITTEN!!!
*  Edits to this file will not be preserved.
*/
// Port_1_3 address and mask defines
#pragma	ioport	Port_1_3_Data_ADDR:	0x4
BYTE			Port_1_3_Data_ADDR;
#pragma	ioport	Port_1_3_DriveMode_0_ADDR:	0x104
BYTE			Port_1_3_DriveMode_0_ADDR;
#pragma	ioport	Port_1_3_DriveMode_1_ADDR:	0x105
BYTE			Port_1_3_DriveMode_1_ADDR;
#pragma	ioport	Port_1_3_DriveMode_2_ADDR:	0x7
BYTE			Port_1_3_DriveMode_2_ADDR;
#pragma	ioport	Port_1_3_GlobalSelect_ADDR:	0x6
BYTE			Port_1_3_GlobalSelect_ADDR;
#pragma	ioport	Port_1_3_IntCtrl_0_ADDR:	0x106
BYTE			Port_1_3_IntCtrl_0_ADDR;
#pragma	ioport	Port_1_3_IntCtrl_1_ADDR:	0x107
BYTE			Port_1_3_IntCtrl_1_ADDR;
#pragma	ioport	Port_1_3_IntEn_ADDR:	0x5
BYTE			Port_1_3_IntEn_ADDR;
#define Port_1_3_MASK 0x8
