//*****************************************************************************
//*****************************************************************************
//  FILENAME: PWM8_12.h
//   Version: 2.60, Updated on 2012/3/2 at 9:15:10
//  Generated by PSoC Designer 5.2.2551
//
//  DESCRIPTION: PWM8 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2012. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PWM8_12_INCLUDE
#define PWM8_12_INCLUDE

#include <m8c.h>

#pragma fastcall16 PWM8_12_EnableInt
#pragma fastcall16 PWM8_12_DisableInt
#pragma fastcall16 PWM8_12_Start
#pragma fastcall16 PWM8_12_Stop
#pragma fastcall16 PWM8_12_bReadCounter              // Read  DR0
#pragma fastcall16 PWM8_12_WritePeriod               // Write DR1
#pragma fastcall16 PWM8_12_bReadPulseWidth           // Read  DR2
#pragma fastcall16 PWM8_12_WritePulseWidth           // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 bPWM8_12_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 bPWM8_12_ReadPulseWidth           // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the PWM8_12 API.
//-------------------------------------------------

extern void PWM8_12_EnableInt(void);                        // Proxy Class 1
extern void PWM8_12_DisableInt(void);                       // Proxy Class 1
extern void PWM8_12_Start(void);                            // Proxy Class 1
extern void PWM8_12_Stop(void);                             // Proxy Class 1
extern BYTE PWM8_12_bReadCounter(void);                     // Proxy Class 2
extern void PWM8_12_WritePeriod(BYTE bPeriod);              // Proxy Class 1
extern BYTE PWM8_12_bReadPulseWidth(void);                  // Proxy Class 1
extern void PWM8_12_WritePulseWidth(BYTE bPulseWidth);      // Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern BYTE bPWM8_12_ReadCounter(void);            // Deprecated
extern BYTE bPWM8_12_ReadPulseWidth(void);         // Deprecated


//--------------------------------------------------
// Constants for PWM8_12 API's.
//--------------------------------------------------

#define PWM8_12_CONTROL_REG_START_BIT          ( 0x01 )
#define PWM8_12_INT_REG_ADDR                   ( 0x0df )
#define PWM8_12_INT_MASK                       ( 0x08 )


//--------------------------------------------------
// Constants for PWM8_12 user defined values
//--------------------------------------------------

#define PWM8_12_PERIOD                         ( 0xff )
#define PWM8_12_PULSE_WIDTH                    ( 0xc0 )


//-------------------------------------------------
// Register Addresses for PWM8_12
//-------------------------------------------------

#pragma ioport  PWM8_12_COUNTER_REG:    0x04c              //DR0 Count register
BYTE            PWM8_12_COUNTER_REG;
#pragma ioport  PWM8_12_PERIOD_REG: 0x04d                  //DR1 Period register
BYTE            PWM8_12_PERIOD_REG;
#pragma ioport  PWM8_12_COMPARE_REG:    0x04e              //DR2 Compare register
BYTE            PWM8_12_COMPARE_REG;
#pragma ioport  PWM8_12_CONTROL_REG:    0x04f              //Control register
BYTE            PWM8_12_CONTROL_REG;
#pragma ioport  PWM8_12_FUNC_REG:   0x14c                  //Function register
BYTE            PWM8_12_FUNC_REG;
#pragma ioport  PWM8_12_INPUT_REG:  0x14d                  //Input register
BYTE            PWM8_12_INPUT_REG;
#pragma ioport  PWM8_12_OUTPUT_REG: 0x14e                  //Output register
BYTE            PWM8_12_OUTPUT_REG;
#pragma ioport  PWM8_12_INT_REG:       0x0df               //Interrupt Mask Register
BYTE            PWM8_12_INT_REG;


//-------------------------------------------------
// PWM8_12 Macro 'Functions'
//-------------------------------------------------

#define PWM8_12_Start_M \
   PWM8_12_CONTROL_REG |=  PWM8_12_CONTROL_REG_START_BIT

#define PWM8_12_Stop_M  \
   PWM8_12_CONTROL_REG &= ~PWM8_12_CONTROL_REG_START_BIT

#define PWM8_12_EnableInt_M   \
   M8C_EnableIntMask(PWM8_12_INT_REG, PWM8_12_INT_MASK)

#define PWM8_12_DisableInt_M  \
   M8C_DisableIntMask(PWM8_12_INT_REG, PWM8_12_INT_MASK)

#endif
// end of file PWM8_12.h
