/******************************************************************************
*  Generated by PSoC Designer 5.2.2551
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PWM16_1.h"
#include "PWM16_2.h"
#include "PWM16_3.h"
#include "PWM16_4.h"
#include "PWM16_5.h"
#include "PWM16_6.h"
#include "PWM16_7.h"
#include "UART_1.h"

#endif
